adam-gotsis 2019 → HTTPConnectionPool(host='localhost', port=51070): Max retries exceeded with url: /session/236f762db1f117078bb3bef5a35e0225/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106d5f1d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
abraham-beauplan 2023 → HTTPConnectionPool(host='localhost', port=51222): Max retries exceeded with url: /session/60c4c56691cdc8268f2bb709c04905bf/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1064e0a90>: Failed to establish a new connection: [Errno 61] Connection refused'))
abraham-lucas 2021 → HTTPConnectionPool(host='localhost', port=51256): Max retries exceeded with url: /session/8bba3133b992d9d5f62d3cbe4f000dfc/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106d5da10>: Failed to establish a new connection: [Errno 61] Connection refused'))
abraham-lucas 2022 → ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
